### ISSUE TITLE
Selecting a cloud provider for this project

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#2]
@dongbohu @cgreene and I were discussing cloud providers to host this webapp. Generally the lab uses AWS. However, I personally find AWS too difficult to use, and at times expensive.

It [looks like](https://cloud.google.com/sql/docs/postgres/quickstart) setting up a Postgres instance on Google Cloud is straightforward. @dongbohu I am inclined to suggest Google Cloud as the first option, and if we find ourselves struggling we can switch to AWS. Just I feel that Google Cloud will make the hosting more accessible to me and I can help with the infrastructure to a larger extent then.

**Comment by dongbohu** [comment]
@dhimmel I don't have a strong preference on which cloud platform to host the database. I never used Google Cloud before. If you think it is better than AWS, then we can definitely try. (As you said, we can switch to AWS if it doesn't work well.)

**Comment by dhimmel** [comment]
Closing this issue since @dongbohu proceeded with AWS.
