### ISSUE TITLE
Continuous deployment fails to update conda environment

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#35]
There are two issues. First, when https://github.com/greenelab/hetmech-backend/commit/ac47bc4508957865570e9f19392362dee3259e89 updated the environment, the [CI deployment failed](https://circleci.com/gh/greenelab/hetmech-backend/107) with error:

```
/home/ubuntu/hetmech-backend/.circleci/deploy.sh: line 13: conda: command not found
```

Second, the `conda env update` command (which is currently incorrect as `conda update`) does not update the pip dependencies (see https://github.com/conda/conda/issues/7774 / https://github.com/conda/conda/issues/8541 / https://github.com/conda/conda/pull/8542). I am thinking we should move to wipe and reinstall the conda env.

**Comment by dhimmel** [comment]
> I am thinking we should move to wipe and reinstall the conda env.

Given that a future conda release will fix this bug, perhaps we can continue with the current `env update` and just fix the first issue of `conda: command not found`.

**Comment by dongbohu** [comment]
`conda` updated to `4.6.14` by this command: `conda update conda`.

**Comment by dhimmel** [comment]
Okay we will see if our fixes close this issue when we merge https://github.com/greenelab/hetmech-backend/pull/38

**Comment by dhimmel** [comment]
https://github.com/greenelab/hetmech-backend/commit/32612caab43856b212ac7cf283ab330e7531d038 [deployed](https://circleci.com/gh/greenelab/hetmech-backend/126) properly and updated hetio, so closing this issue.
