### ISSUE TITLE
count-metapaths-to not returning metapath_count

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#53]
https://search-api.het.io/v1/nodes/?search=Alitretinoin&limit=100&count-metapaths-to=20115 returns

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 21150,
            "identifier": "DB00523",
            "identifier_type": "str",
            "name": "Alitretinoin",
            "properties": {
                "url": "http://www.drugbank.ca/drugs/DB00523",
                "inchi": "InChI=1S/C20H28O2/c1-15(8-6-9-16(2)14-19(21)22)11-12-18-17(3)10-7-13-20(18,4)5/h6,8-9,11-12,14H,7,10,13H2,1-5H3,(H,21,22)/b9-6+,12-11+,15-8-,16-14+",
                "source": "DrugBank",
                "license": "CC BY-NC 4.0",
                "inchikey": "InChIKey=SHGAZHPCJJPHSC-ZVCIMWCZSA-N"
            },
            "metanode": "Compound"
        }
    ]
}
```

Note that `metapath_count` is missing, but there should be results:

![image](https://user-images.githubusercontent.com/1117703/58586216-9284f300-8228-11e9-8abc-ef9a42312194.png)

**Comment by dhimmel** [comment]
@vincerubinetti it seems to me that count-metapaths-to never works when `search` is specified.

**Comment by dhimmel** [comment]
I amended the last commit to https://github.com/greenelab/hetmech-backend/commit/e73ccb4363f669ba04119a798d2ff579dd7f83b7, this should fix it I hope! I fixed this last week but forgot to push upstream. The issue is that the code had `count_metapaths_to` rather than `count-metapaths-to`.

**Comment by vincerubinetti** [comment]
Odd. I could've sworn this was working before, that is `count-metapaths` with `search` specified.

**Comment by dhimmel** [comment]
Amending commit broke backend https://circleci.com/gh/greenelab/hetmech-backend/190 @dongbohu we need to force pull and in future I will protect master branch

**Comment by dongbohu** [comment]
I did force pull on backend server. It should be working as it was before the amending.
