### ISSUE TITLE
Add metatype filter to all applicable queries

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/connectivity-search-backend#58]
We have a handy collection of metatype filter buttons at the top of the page on the front end. Currently, the only query those have an effect on is when the user types in a search string. It doesn't apply when doing `count-metapaths-to` or anything else.

We can sit down and discuss where it would be appropriate to include this parameter. It might just be all the queries involved with the source/target search bars, as making the filter buttons have an effect on something much further down the page might be confusing to the user.

**Comment by cgreene** [comment]
It seems like if we're going to have the filters on the page, they probably should apply to the full set of queries. I think this came up on the call this week where the "fill in the second element" wasn't filtered.

**Comment by dhimmel** [comment]
Indeed. I'll look into what the backend API needs in order to support consistent filtering.

**Comment by dhimmel** [comment]
Check out https://github.com/greenelab/hetmech-backend/pull/66.

Once merged, it will allow queries like https://search-api.het.io/v1/count-metapaths-to/2/?metanodes=G,MF

This query would return cached metapath counts from node 2 to all nodes of type Gene or Molecular Function. The change is backwards compatible... omitting `?metanodes=G,MF` will continue to return counts for all nodes.

@vincerubinetti I think this is all we need in terms of the backend to resolve this issue, but let me know if other endpoints also need this functionality.

We could also support metanode filtering for `random-node-pair`...
