### ISSUE TITLE
populate_database.py: "data" should be "properties"

### ISSUE THREAD

**Issue by LuciaWL001** [greenelab/connectivity-search-backend#73]
The line 216 in populate_database.py is wrong.
It shoud be changed from data=data to properties=data.
Please check and confirm.
Thank you~

**Comment by dhimmel** [comment]
Here's the command in question:

https://github.com/greenelab/connectivity-search-backend/blob/c70881828b58310722426f61550596950bb1a61b/dj_hetmech_app/management/commands/populate_database.py#L210-L217

Looks like we forgot to update `populate_database.py` following https://github.com/greenelab/connectivity-search-backend/commit/b65186eadf8dd0f94e70a40f80eca9e27065e2d1. Great catch @LuciaWL001.

Would you like to submit a pull request to fix this issue and any other you encounter? I think that's a nice way for you to get credit for you contributions. If not, I can do it, but wanted to give you a chance first.

**Comment by LuciaWL001** [comment]
Thank you for your response~
I will try to pull a request and fix the issue. But it's my first time to fix issue in github，I will try my best to do it carefully.

**Comment by LuciaWL001** [comment]
I am sorry I can not git clone code from github right now, due to the bad network. Please fix it by yourself.
Thank you for your trust.

**Comment by dhimmel** [comment]
Okay should be fixed by https://github.com/greenelab/connectivity-search-backend/commit/af12f8cf2ad47d9a25ce8d1b7889390654eb3bb9. Let me know if you encounter any other problems!
