### ISSUE TITLE
search-api.het.io SSH access and main branch rename

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#76]
I renamed the default branch to `main` and updated source in https://github.com/greenelab/connectivity-search-backend/commit/3c4e558afc3f7cb01b816254e86dcf98b073f85e.

Looking at the [CI Logs](https://app.circleci.com/pipelines/github/greenelab/connectivity-search-backend/227/workflows/9ca649e6-1522-48ad-a99e-ddbc8536ce53/jobs/276), I'm not sure the auto-deploy is working for the `main` branch:

```
Already on 'master'
Your branch is up to date with 'origin/master'.
Fetching origin
From https://github.com/greenelab/hetmech-backend
 * [new branch]      main       -> origin/main
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

Tried SSHing into the instance using `ssh ubuntu@search-api.het.io`, but got "Permission denied (publickey)". @dongbohu can you add my public SSH keys from [here](https://github.com/greenelab/public-keys/blob/master/ssh/dhimmel.pub).

Also I think you were planning to migrate to AWS, similar to https://github.com/hetio/hetionet/issues/35. The migration will probably take care of the any issues with new default branch name I imagine? The issue that I think might be occurring is that instance is still on the `master` branch and not `main`?

**Comment by dongbohu** [comment]
@dhimmel I added all your ssh keys. I took a quick look at the serer on AWS. Yes, it is still on `master` branch. Let's deal with this issue when it is migrated to Google Cloud.

**Comment by dhimmel** [comment]
Thanks for adding the SSH key. I logged in and switched the branch to main.

```
git branch --verbose
* main 640a6b3 readme: pg_dump download & public database
```
