### ISSUE TITLE
Migrate hosting to GCP from AWS

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#78]
From @dongbohu:

> Daniel, I created a new database and a new virtual machine on Google Cloud Platform to host the connectivity-search API. Please take a look at it:
> http://35.229.106.21/v1/
> If it looks okay with you, please register the IP address "35.229.106.21" with "search-api.het.io". When the registration gets effective, I will install an HTTPS certificate and enable HTTPS. The migration will be done.

**Comment by dhimmel** [comment]
Okay I updated the DNS record to be:

```
search-api 1000 IN A 35.229.106.21
```

So now you can generate the SSL certifacte?

Does this migration only affect `search-api.het.io` and not the postures database at `search-db.het.io`? Are you also planning to migrate the database?

**Comment by dongbohu** [comment]
Thanks @dhimmel. I enabled HTTPS and the new https://search-api.het.io seems to be  alive now.

The new API server actually is using a new database, whose IP address is `35.229.78.195`. Please feel free to update `search-db.het.io` too.

**Comment by dhimmel** [comment]
Okay updated that DNS record as well, so the records are now:

```
search-api 1000 IN A 35.229.106.21
search-db 1800 IN A 35.229.78.195
```

So the old database and instance can go now?

**Comment by dongbohu** [comment]
I have stopped the original EC2 and RDS instances on AWS. Will keep it for a few more days. If everything is okay, I will delete them permanently.
