### ISSUE TITLE
Use a clean git repo in the production search-api.het.io instance

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#81]
Following #78 & https://github.com/greenelab/connectivity-search-backend/pull/80, I noticed the following unstaged change in the git repo on search-api.het.io:

```patch
diff --git a/dj_hetmech/settings.py b/dj_hetmech/settings.py
index 9b9bdd9..691968f 100644
--- a/dj_hetmech/settings.py
+++ b/dj_hetmech/settings.py
@@ -29,7 +29,7 @@ with open(path) as read_file:
 SECRET_KEY = 'secret_not_yet_set'
 
 # SECURITY WARNING: don't run with debug turned on in production!
-DEBUG = True
+DEBUG = False
 
 ALLOWED_HOSTS = ['localhost', 'search-api.het.io', ]
```

This seems problematic to me. If we change `settings.py` it could cause the `git pull --ff-only` to fail. There must be a more robust way of setting DEBUG false? For example, by way of an environment variable or other option passed to django? @dongbohu what do you think?

**Comment by dongbohu** [comment]
Good point. I think we can set `DEBUG` and `SECRET_KEY` in `secrets.yml`. If they are not found in `secrets.yml`, default them to:
```
SECRET_KEY = 'secret_not_yet_set'
DEBUG = True
```
Do you want to include that in the PR that you are working on now?

**Comment by dongbohu** [comment]
I created a local branch on search-api.het.io, so its local `main` branch is in sync with the repo. When your changes are merged, `git pull --ff-only` should be okay.

**Comment by dhimmel** [comment]
> Good point. I think we can set DEBUG and SECRET_KEY in secrets.yml. If they are not found in secrets.yml, default them to:

I like this idea.

> Do you want to include that in the PR that you are working on now?

Would prefer to have this as a separate PR.

> When your changes are merged, git pull --ff-only should be okay.

So the instance is currently not on the main branch?

**Comment by dongbohu** [comment]
I found DEBUG was True in the evening, so I created a new branch and set it
to False, then deployed it on production. We can have deploy it on "main"
branch after this is fixed.

**Comment by dongbohu** [comment]
I filed a quick PR #82 for this issue.
