### ISSUE TITLE
https://search-api.het.io/ is currently down or inaccessible

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-backend#83]
```
ping https://search-api.het.io/
ping: https://search-api.het.io/: Name or service not known
```

And on https://het.io/search/, looking at the console for search API requests, we're getting `ERR_CONNECTION_TIMED_OUT`.

@dongbohu can you look into this?

**Comment by dongbohu** [comment]
@dhimmel For some reason the backend server was dead. I rebooted it and it seems to be working now.

**Comment by dhimmel** [comment]
Thanks @dongbohu. Noting https://github.com/hetio/hetionet/issues/38: the Neo4j database also went down around the same time. Not sure if there is any relation.
